### ISSUE TITLE
More padding, higher DPI for small equations

### ISSUE THREAD

**Issue by jassler** [daskol/typst-telegram-bot#7]
Love the bot! There's some things I noticed when using it:

* A padding around the math expression would be nice, otherwise it looks awfully crammed. This also causes parts of the equations to be hidden behind the timestamp of the message (see screenshot below);
* Small expressions appear pixelated;
* Emojis are not supported (they do render fine when using Typst, maybe it's an issue with the web framework);

I wanted to contribute to the project, but I'm having a hard time following the documentation in the README (ie. where is the command `typst-telegram` coming from? How do I host a simple HTTP API to `typst`?)

From what I've seen in `render.py`, I tried running `typst compile --diagnostic-format=short --format=png --ppi=300 tmp.typ tmp.png` to see if there's a way to add padding from compiling a Typst file. To my surprise, the png output has the format of an entire pdf document. I didn't see any part in your code where you crop the image. Am I doing something wrong?

<img width="534" alt="image" src="https://github.com/daskol/typst-telegram-bot/assets/24298790/36dd8f16-a0bd-4bd8-8ff4-3d4c9517a7b2">

**Comment by daskol** [comment]
Thanks for using the bot! I'm glad that you find it useful. :smile:

> A padding around the math expression would be nice, otherwise it looks awfully crammed.

What do you think about padding size of [t.me/InLaTeXbot][3]? Not too big?

> Small expressions appear pixelated;

This is because shape of image in pixels (height and width) depends on a font size, ppi, and text to render while Telegram tries to fit image of any size to fixed viewport. Padding could mitigate the issue. Also, Telegram compress images what affect image quality too.

> Emojis are not supported (they do render fine when using Typst, maybe it's an issue with the web framework);

Good point. Emojis are supported but fonts with emoji are missing. I'll install them into container.

> where is the command typst-telegram coming from?

It's classic Python entrypoint scripts (see [`pyproject.toml`][1] for details).

> How do I host a simple HTTP API to typst?

Command `typst-telegram` allows to serve API but the simplest way to run server is spawn docker container with compose (see [`docker-compose.yml`][2]).

> To my surprise, the png output has the format of an entire pdf document.

This is why you should set page geometry as follows.

```typst
#set page(width: auto, height: auto, margin: (x: 0pt, y: 0pt))
$ ... $
```

[1]: https://github.com/daskol/typst-telegram-bot/blob/v0.2.0/pyproject.toml#L42-L43
[2]: https://github.com/daskol/typst-telegram-bot/blob/v0.2.0/docker-compose.yml#L3-L11
[3]: http://t.me/InLaTeXbot

**Comment by jassler** [comment]
Thanks for the quick reply!

> What do you think about padding size of [t.me/InLaTeXbot](http://t.me/InLaTeXbot)? Not too big?

Oh, good find, didn't know that bot existed. In my taste, yeah, the padding seems a little too big. I think, just a little bit of whitespace would suffice, maybe something like this:

<img width="247" alt="image" src="https://github.com/daskol/typst-telegram-bot/assets/24298790/4cbb1e49-2984-4d6a-9fac-aeb025e06ffb">

> This is because shape of image in pixels (height and width) depends on a font size, ppi, and text to render while Telegram tries to fit image of any size to fixed viewport. Padding could mitigate the issue.

Good point, maybe some padding is all that's needed. Maybe you can also specify a minimum image size (i.e., if it's smaller than 100x100, pad it to make it 100x100 big).

Thank you for the points on setting up the project, I'll try it tonight.

> ```typst
> #set page(width: auto, height: auto, margin: (x: 0pt, y: 0pt))
> $ ... $
> ```

Oh, this is smart. So maybe just setting the margin is the simplest solution, right?

**Comment by daskol** [comment]
More fonts and margins have added in the new release [v0.2.1](https://github.com/daskol/typst-telegram-bot/releases/tag/v0.2.1). It has already deployed. Check it.

**Comment by jassler** [comment]
Perfect, I love it 😄

As for the resolution, do you think using a bigger font would make a difference?
